### ISSUE TITLE
Tagged v3.0 on wrong commit

### ISSUE THREAD

**Issue by fourstacks** [Weble/laravel-playbooks#62]
Hey @Skullbock - it looks like you may have tagged v3.0 on the wrong commit.  If you tag a look at the source for that tag (https://github.com/Weble/laravel-playbooks/releases/tag/3.0) you'll see that the `composer.json` still references the older versions of illuminate.  If you try to install in a L9 project composer squawks at you and won't resolve dependencies.

If you get a moment to tag a 3.0.1 on the latest commit then that should sort things out.  I'll just use `dev-master` for now.  Thanks!

**Comment by Skullbock** [comment]
Whoops what a noob error.
Tagged 3.0.1
